version: '2'

# This Compose file can be used in a development environment.
#
# Useful commands:
#
# Run this: docker-compose -f docker-compose-dev.yml down && docker-compose -f docker-compose-dev.yml up -d --build
# Restore DB dump: docker exec -i tq_website_db_1 mysql -u root -p"ROOTPASSWORD" tq_website < dump.sql
# Connect to Postgres: docker exec -it tq-postgres psql -U root -d tq_website

services:
  # Database (MySQL)
  db:
    image: mysql:8
    container_name: tq-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${TQ_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: tq_website
    command: [--default-authentication-plugin=mysql_native_password]
    volumes:
      - "db-volume:/var/lib/mysql"
    ports:
      - "${TQ_DB_PORT}:3306"
    restart: always

  # Database (Postgres)
  postgres:
    image: postgres:12
    container_name: tq-postgres
    environment:
      POSTGRES_USER: ${TQ_DB_USER_POSTGRES}
      POSTGRES_PASSWORD: ${TQ_DB_PASSWORD_POSTGRES}
      POSTGRES_DB: tq_website
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    ports:
      - "${TQ_DB_PORT_POSTGRES}:5432"
    restart: always

  # Cache
  redis:
    container_name: tq-redis
    image: redis:3.2-alpine
    restart: always

  # Django (serving with debug webserver)
  django:
    container_name: tq-django
    build:
      context: .
      dockerfile: configurations/dockerfile
    image: tq_website_django # give this built image a name to use it below
    env_file:
      - .env
    user: root
    volumes:
      - .:/webapps/tq_website:Z
    command: python3 -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - "${TQ_DJANGO_PORT}:8000"
    links:
      - db
      - postgres
      - redis
    restart: always
    depends_on:
      - db

volumes:
  db-volume: # Let Docker generate a place for this, doesn't matter for development
  postgres-volume: # Let Docker generate a place for this, doesn't matter for development
